### ISSUE TITLE
Usage of scReadCounts for single nucleotide variant calling from 10X scRNAseq data of haploid genomes

### ISSUE THREAD

**Issue by JesseRop** [HorvathLab/NGS#13]
Dear developers,

Thanks for the great tool!  I'm excited to try it after reading your paper but just wanted to confirm whether it can be used for 10X scRNAseq data of haploid organisms where we don't expect heterozygotes.

Thanks,
Jesse

**Comment by edwardsnj** [comment]
Hi Jesse, I don't think that'll be an issue. Let me know if you have trouble getting things to work.

**Comment by edwardsnj** [comment]
Closing since the user didn't indicate any issue...
