### ISSUE TITLE
scSNViz_1web

### ISSUE THREAD

**Issue by AneliaHorvath** [HorvathLab/NGS#27]
From NE:
All of these figures should all be embedded in a single HTML page,
generated by the script, with text on the page explaining what they are.
There should be a table of the loci that points to the individual loci
plots. The site should link to the example output page (so users can
browse from the site) and understand what is on offer. The STARsolo
output example should be provided. Ideally a complete example, including
STARsolo alignment, SCReadCounts, etc. should be shown.

In addition, small changes in the existing scSNViz script, as below:

1) Change the default color to YlOrRd
2) Update the help options based on the github text

**Comment by tushar2016sharma** [comment]
Update:

I combined all the 3D plots into one single html page which would be entitled 'sample-SNVs-combined' once the script is executed. A major chunk of the code which dealt with the generation of the 3D plots has been modularized by replacing with a single function that generates them. The small changes - default color to YlOrRd and updating help options has been done.   

Questions:

1. Are the 2D plots (histograms) also required to be combined in the same html page? 
2. The last chunk of code (plot sctype with slingshot trajectories and plot that contains VARreads, REFreads, etc.) in the original code is a little unclear to me. I notice that it plots the individual lineages. For now, I have commented it out, but let me know and I can try to integrate it. 

I have emailed the R script (as the format isn't supported to attach here) Let me know any suggestions/corrections on the aesthetics in the combined plots.
