### ISSUE TITLE
scReadCounts with strand information

### ISSUE THREAD

**Issue by lucia-ramirez** [HorvathLab/NGS#6]
Hi, 

Would it be possible to have the counts by strand? This would be helpful for variants overlapping multiple transcripts where one is in the opposite direction. 

Many thanks, 

Lucia

**Comment by edwardsnj** [comment]
Hi Lucia, this is quite feasible, the underlying readCounts table contains this information. I will be releasing a new release of ReadCounts and SCReadCounts shortly, and I will add this feature to scReadCounts.

**Comment by edwardsnj** [comment]
Hi Lucia, I have added the requested feature to scReadCounts (--directional) in [release 1.2.0](https://github.com/HorvathLab/NGS/releases/tag/SCReadCounts-1.2.0). Let me know if you have any questions or problems with this feature.
