### ISSUE TITLE
usage of table_browser_to_SCRC.py

### ISSUE THREAD

**Issue by rosaranli** [HorvathLab/NGS#8]
I was trying to get the read counts from 10X single cell RNA seq data so was going to try the discovery mode as I don't have the matched Exom data to have an initial list of SNPs. Can I ask how to use table_browser_to_SCRC.py? would it be like 
python table_browser_to_SCRC.py sampel_R2.fastq.gz output.file ?

I got confused as fastq files doesn't have mapping information, how could we get the list of SNPs from it?

Thank you very much!

**Comment by edwardsnj** [comment]
Hi Ran, sorry, I lost track of this.

For SCReadCounts, the discovery mode stuff was written by a previous member of the lab, and its kinda a hack.

It takes a FASTA file generated by the UCSC genome browser with genomic coordinates embedded in the defline. It presumes the genomic coordinates in this FASTA file correspond to the genomic coordinates of your aligned BAM file of RNA sequencing reads. It then uses the sequence in the FASTA file as the reference nucleotide at every single locus and enumerates the other nucleotides. As such it essentially checks every single position three times. You can see all of this in the examples and pictures in the My_scripts repository provided by Prashant. 

This will be very slow unless you are interested in a very small region. 

There are better approaches unless you are really desperate. :-)

Let me know if you are still interested in this, and I'll see if I can come up with a better solution.

**Comment by rosaranli** [comment]
Hi Edwards, thank you very much for your reply. I am still interested in this. For a particular question, I am interested in the chr 3p region and want to check the allelic balance of this region. For example, if it is a homozygous region or not.

**Comment by rosaranli** [comment]
Hi Edwards, thank you very much for your reply. I am still interested in this. For a particular question, I am interested in the chr 3p region and want to check the allelic balance of this region. For example, if it is a homozygous region or not. 

Could you please propose a better solution? If not, I would like to try every single base but I would assume it will be very slow. So would you explain how to use the script in detail? Like input and output if there are no other better solutions? 

I really appreciate your help!

**Comment by edwardsnj** [comment]
OK, tomorrow I will push a new release with a tool to output putative variant loci based on the BAM file alone. This won't (yet) be single-cell or UMI aware or even genetically reasonable, but they will have at least n reads with a specific change from the reference at each locus. You will have to use SCReadCounts to count the reads at each of these loci per cell to decide whether they are biologically reasonable. 

This should be much faster than trying every single locus three times. 

- n

**Comment by edwardsnj** [comment]
Hi Ran, I have (finally) pushed a [new release of SCReadCounts](https://github.com/HorvathLab/NGS/releases/tag/SCReadCounts-1.3.0) that includes an experimental tool `varLoci` for de novo extraction of *potential* variant loci directly from the BAM file. See the documentation of [Discovery Mode](https://github.com/HorvathLab/NGS/blob/master/SCReadCounts/docs/Discovery.md). Let me know if it works effectively for you.

**Comment by rosaranli** [comment]
Thank you very much for the new release and It will be really useful. I did a test run and the error is "tag 'NM' not present". I used the bam file generated by cell ranger and I couldn't see the "NM" tag in the list of "barcoded BAM Tags "from cell ranger. Can you advise how I can avoid this error?

**Comment by edwardsnj** [comment]
> Thank you very much for the new release and It will be really useful. I did a test run and the error is "tag 'NM' not present". I used the bam file generated by cell ranger and I couldn't see the "NM" tag in the list of "barcoded BAM Tags "from cell ranger. Can you advise how I can avoid this error?

Hmmm. Looks like Cell Ranger (which is based on STARSolo!) does not output NM (edit distance of the alignment as STARSolo does), but instead outputs nM (number of mismatches of the alignment). *eye roll*

If you can, could you please use samtools view to dump a few rows of the SAM format so I can see what tags are in the Cell Ranger file? 

I've tweaked the code to check for NM and nM before using either to try to speed things up. 

I will send you a link to have you test out this new version...

**Comment by edwardsnj** [comment]
Oh, and can you copy and paste the entire traceback (not just the error message?) Also, are you running the Linux, MacOS or Python release? Thanks

**Comment by edwardsnj** [comment]
Thanks for confirming what I thought (location of the use of the NM tag). This is what I fixed in the unofficial version I sent you a link for, let me know if varLoci runs correctly now.

**Comment by edwardsnj** [comment]
mincount is the minimum number of reads that have the alternative allele. I'll make the documentation clearer.
